### PR TITLE
add command_open_tab_near_current

### PR DESCRIPTION
**Pull request by zhuochun**
solve #300 open new tab next to the current tab.

### CODE REVIEW

**Comment by TheGreenHabi** [comment]
btw, is there any particular reason why this patch is not implemented? Seems like nice function to have

**Comment by lydell** [comment]
Yes, it might be useful. I don't like the implementation, though. It makes too many assumptions.

**Comment by TheGreenHabi** [comment]
I will see what I can do about this

**Comment by TheGreenHabi** [comment]
@lydell, what do you think of this implementation?

```coffeescript
command_open_tab_near_current = (vim) ->
  { gBrowser } = vim.rootWindow

  currentTab = vim.rootWindow.gBrowser.selectedTab
  newTabPosition = currentTab._tPos + 1

  vim.rootWindow.BrowserOpenTab()
  currentTab = vim.rootWindow.gBrowser.selectedTab
  gBrowser.moveTabTo(currentTab, newTabPosition)
```
Or short variation:

```coffeescript
command_open_tab_near_current = (vim) ->
  { gBrowser } = vim.rootWindow
  newTabPosition = vim.rootWindow.gBrowser.selectedTab._tPos + 1
  vim.rootWindow.BrowserOpenTab()
  gBrowser.moveTabTo(vim.rootWindow.gBrowser.selectedTab, newTabPosition)
```

**Comment by lydell** [comment]
That's a lot better! However, it still assumes that the new tab will be focused.

**Comment by TheGreenHabi** [comment]
I hope I understand correctly. Focused means that newly created tab becomes currently active tab.
What behavior you want it to have? I assume that if I create new tab it will be focused.

**Comment by lydell** [comment]
See, there you just summarized the different problems and different possibilities. Thanks.

**Comment by TheGreenHabi** [comment]
Yeah... I just found a way to firefoxception))) By analogy to Inception movie.
chrome://browser/content/

**Comment by lydell** [comment]
I’ve added a variation of @TheGreenHabi’s implementation to the [Custom Commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands) section of the wiki.

**Comment by lydell** [comment]
I finally found a way to do this reliably and have added it in the development version!

**Comment by TheGreenHabi** [comment]
Great! Thank you for your work!

**Pull request closed without merging**
