### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by millysoose**
First pull request. Added support for the firenvim extension.

### CODE REVIEW

**Comment by millysoose** [comment]
uh this is a little embarrassing but after more testing it seems that did not fix it. I think when I installed the xpi it temporarily broke VimFX and I was able to interact with firenvim's embedded terminal without interference. I'm going to read a little more into the code and see what's going on.

**Comment by girst** [comment]
just so you know: i am more than happy to merge support for this other 
extension ;-)

if you're getting stuck, let me know!

**Comment by millysoose** [comment]
> just so you know: i am more than happy to merge support for this other extension ;-) if you're getting stuck, let me know!
Thanks. Could you clarify the difference between the isIgnoreFocusType and is IsIframeEditor functions? I noticed the wasavi extension, an Iframe editor, is checked for by both functions. This seems to be related to ignore mode (red icon) and the mode VimFx uses inside text forms (grey icon).

**Comment by girst** [comment]
On Sun, May 03, 2020 at 01:05:57PM -0700, millysoose wrote:
>Thanks. Could you clarify the difference between the isIgnoreFocusType 
>and is IsIframeEditor functions?

uhhh...good question! i believe, isIframeEditor is intended for editors 
that are provided by the website itself (like on 
https://shellcheck.net), and isIgnoreModeFocusType for other extensions 
that replace normal <textarea>s and <input>s.  keep in mind, i'm no 
expert at vimfx either; i'm just the janitor keeping the place from 
deteriorating too much / last guy here, refusing to turn off the lights 
after the party ended.

**Comment by millysoose** [comment]
> uhhh...good question! i believe, isIframeEditor is intended for editors that are provided by the website itself (like on https://shellcheck.net), and isIgnoreModeFocusType for other extensions that replace normal <textarea>s and <input>s. keep in mind, i'm no expert at vimfx either; i'm just the janitor keeping the place from deteriorating too much / last guy here, refusing to turn off the lights after the party ended.

Well I really appreciate your upkeeping because I'm not ready to leave either.

Back to the problem: In this case, a proper check in isIgnoreModeFocusType should be all that's needed. Yet...it isn't working out. The check I added for firenvim looks for the value of its src attribute using `element.src?.endsWith('NeoVimFrame.html')`. This could evaluate true and VimFX should enter the ignore mode when focused on this element. Though, when theories don't equate to reality, it may be time to revise the theories :).

**Comment by girst** [comment]
On Sun, May 03, 2020 at 01:44:18PM -0700, millysoose wrote:
>Back to the problem: In this case, a proper check in 
>isIgnoreModeFocusType should be all that's needed. Yet...it isn't 
>working out. The check I added for firenvim looks for the value of its 
>src attribute using `element.src?.endsWith('NeoVimFrame.html')`. This 
>could evaluate true and VimFX should enter the ignore mode when focused 
>on this element. Though, when theories don't equate to reality, it may 
>be time to revise the theories :).

i don't really know what could cause it to not work. I guess, you 
already verified assumptions with console.log()? you can also debug 
vimfx with the Browser Toolbox (ctrl-alt-shift-i; requires 
devtools.debugger.remote-enabled and devtools.chrome.enabled).

**Comment by millysoose** [comment]
> i don't really know what could cause it to not work. I guess, you already verified assumptions with console.log()? you can also debug vimfx with the Browser Toolbox (ctrl-alt-shift-i; requires devtools.debugger.remote-enabled and devtools.chrome.enabled).
It seems the browser toolbox (ctrl-alt-shift-i) is restricted from accessing variables on the page.
For example, console.log(element, " ", element.src) will output <unavailable> undefined when focusing on page elements. When focusing on browser elements such as the URLbar, it works properly.
Perhaps I am doing something wrong?

**Comment by girst** [comment]
On Mon, May 04, 2020 at 01:33:44PM -0700, millysoose wrote:
>For example, console.log(element, " ", element.src) will output 
><unavailable> undefined when focusing on page elements. When focusing 

ohh, i remember running into this issue! you'll have to serialize it 
before passing it to console.log(). For example using JSON.stringify() 
or elem.outerHTML (whatever seems suitable for the information you want 
to extract). i believe that this is because the page runs in a different 
process ("content process" in mozilla speak) to the browser ui 
("chrome").

>on browser elements such as the URLbar, it works properly.

setting breakpoints should work as well. if you run into one, you can 
switch to the "console" tab and have access to all variables.

testing/debugging in firefox nightly might be worth a shot, too, since 
the developer tools there are often a step better.

**Pull request closed without merging**
