### PR TITLE
Translation to pt-BR.

### PR DESCRIPTION
**Pull request by atilacamurca**
I took the liberty to include a `vimfx.pot` file to help translators to use PO tools such as POEdit or Gtranslator.
Also I include a `pt-BR.po` file to help me translate and others later.

I use the [Translator Toolkit](http://translate-toolkit.readthedocs.org/en/latest/index.html) which helps me convert from `.properties` to `.po`.
For reference check this out <http://translate-toolkit.readthedocs.org/en/latest/commands/prop2po.html>

As an open source project, I suggest you start using Transifex to translate. It's free for open source projects and it's great.

### CODE REVIEW

**Comment by lydell** [comment]
Ouch. I just pushed a major refactor I’ve been working for a while, which unfortunately makes your translation obsolete :(

I’d suggest the following:

1. Rebase on latest develop.
2. Only include the description and vimfx.properties in this PR.
3. Open a separate issue about using some translation tool/service, convincing me to do it, because that’s not what I feel like spending time on right now.

**Comment by atilacamurca** [comment]
It's ok to just redo in the same PR?

**Comment by lydell** [comment]
Yes

**Comment by atilacamurca** [comment]
I just add the new commit can you review and merge?

**Comment by lydell** [comment]
The translation looks good! :+1: You still need to do this, though:

> Only include the description and vimfx.properties in this PR.

Then please squash into one commit and force push.

**Comment by lydell** [comment]
When doing the above, you might want to rebase on develop again. Don’t worry, no big changes this time. I’ve simply just added one more string to translate :)

**Comment by atilacamurca** [comment]
Phew! Now I think it's good to go!

**Comment by lydell** [comment]
1. `git rebase --interactive 2a06c919^`
2. In the editor that shows up, change “pick” into “squash” bottom-most of your commits.
3. Save and close the editor.
4. In the editor that shows up, edit the two commit messages into for example “Add pt-BR translation”.
5. Save and close the editor.
6. `git push --force`.

**Comment by atilacamurca** [comment]
Great, thanks for the explanation. It help me a lot.

That's the beauty of open source projects, how much you learn from it.

**Comment by lydell** [comment]
> That's the beauty of open source projects, how much you learn from it.

Yes, I agree. I remember when I started contributing to this project @akhodakivskiy helped me with git a couple of times as well :)

Thank you very much for your contribution! Now don’t forget to open that separate issue, if you feel like it.

---

In case you need to rebase things with git in the future, the thing to remember is: Run `git rebase --interactive <sha>` where `<sha>` is the `<sha>` of the commit just before the one you want to rebase from. (The `^` at the end above means the commit before.) Then just follow the instructions (git is helpful enough to guide you along the way).

**Pull request merged**
