### PR TITLE
Make scrolling commands scroll the focused element

### LINKED ISSUE #11: Переключение фокуса контейнеру / Scoll focus on the container
Хорошо бы как-то иметь возможность переключаться и прокручивать не только главное окно, но и контейнер с включенными скроллами. Как например тут https://dl.dropbox.com/u/44239143/scroll_container.png

There are two distinct issues:
- Ability to scroll individual containers that have scroll bars on the page is desired. 
- Currently VimFx uses `window.scrollBy` which won't work on the webpage that has custom layout where `window` has fixed height, and there is inner scrollable container. VimFx should be able to scroll in on such pages using `j/k`.

### PR DESCRIPTION
**Pull request by lydell**
Fixes #11. If the currently focused element is scrollable, it is scrolled by the
scrolling commands. Otherwise the largest scrollable element (usually the whole
ocument) is scrolled.

In other words, you may now choose which element to scroll with the 'f' or 'vf'
command, and then you can scroll it with the scroll commands.

This requires Firefox 36 or later and must not be merged before that version is released as stable.

### CODE REVIEW

**Comment by lydell** [comment]
TODO:

- Honor `general.smoothScroll` (and possibly `general.smoothScroll.lines` etc) pref(s).
- Replace scroll step with `toolkit.scrollbox.horizontalScrollDistance` and `toolkit.scrollbox.verticalScrollDistance`.

But let’s wait until we know more about <https://bugzilla.mozilla.org/show_bug.cgi?id=1045754#c35> and <https://bugzilla.mozilla.org/show_bug.cgi?id=1129063>. No rush until Firefox 36 is released.

**Comment by lydell** [comment]
All TODOs fixed.

**Comment by lydell** [comment]
TODO: layout.css.scroll-behavior.spring-constant needs to be set to a larger value automatically: see https://bugzilla.mozilla.org/show_bug.cgi?id=1131740. Then we can merge.

**Comment by lydell** [comment]
Done.

**Comment by jck** [comment]
I had to set layout.css.scroll-behaviour.spring-constant manually after building and installing the current dev branch.

**Comment by lydell** [comment]
What do you mean?

**Comment by jck** [comment]
Sorry, I mean this:
> TODO: layout.css.scroll-behavior.spring-constant needs to be set to a larger value automatically 

is not happening for me. I needed to change it manually.

**Comment by lydell** [comment]
What do you set it to?

**Comment by jck** [comment]
I tried 2500, but even with that the scrolling doesn't feel good. I've switched back to the stable version for now.

**Comment by lydell** [comment]
> ... is not happening for me. I needed to change it manually.

Do you know that it is not happening for you because the scrolling feels slower compared to Firefox builtin scrolling (_not_ compared to VimFx 0.5.x!)? Just looking in about:config is not enough, because VimFx only temporarily changes the pref and then switches back again.

Also, have you tried changing any of the following prefs?

> The scrolling commands respect built-in Firefox prefs:
> 
> - general.smoothScroll: Turn smooth scrolling on/off for _all_ scrolling
>   commands.
> - general.smoothScroll.lines: h, j, k, l only.
> - general.smoothScroll.pages: d, u, <space>, <s-space> only.
> - general.smoothScroll.other: gg, G only.
> - toolkit.scrollbox.horizontalScrollDistance: Scroll step for h, l.
> - toolkit.scrollbox.verticalScrollDistance: Scroll step for j, k.
> 
> The two last prefs replace the scroll step setting.
> 
> A bunch of new (hidden) prefs let you customize the smooth scrolling, in the
> same spirit as the built-in `general.smoothScroll.<type>.duration{Min,Max}MS`.
> They're called `smoothScroll.<type>.spring-constant` and work like
> `layout.css.scroll-behavior.spring-constant`.

Lastly, it would be very helpful if you could elaborate on “the scrolling doesn’t feel good”. Is it too slow? Is it janky? Are all of VimFx scrolling commands affected? Etc.

**Comment by jck** [comment]
@lydell , Sorry I missed your reply.

I recompiled the latest dev version, and ensured that all the prefs you mentioned were at their defaults.

I want to say that the scroll speed is slower, but I'm not sure about that.
It could also be that the scroll acceleration is lower than before, so it takes longer to get somewhere while holding j/k.

I would appreciate some directions on how to change the prefs to emulate the scrolling behaviour of the current stable version.

**Comment by lydell** [comment]
> I want to say that the scroll speed is slower, but I'm not sure about that.

I took great care to set the default scroll speeds for the various scroll commands to match Firefox's default scroll speed. I don't know if that matches the speeds used in the current stable version. What do you compare with?

> it takes longer to get somewhere while holding j/k

Yes, that's true, and a bit unfortunate. I'd luke them to work like the arrow keys, but haven't found a way yet. IMO that is acceptable, though, since holding j/k is an anti-pattern: it is much more efficient to scroll by pages.

**Comment by jck** [comment]
https://xkcd.com/1172/

I guess I should just stop depending on holding j/k.

**Pull request merged**
