### PR TITLE
-moz-document gone

### LINKED ISSUE #904: not work with Firefox 20171203, -moz-document gone
It seems that `-moz-document` is no longer supported in XUL addons, so the styles are gone. I tried to remove that declaration from skin/style.css, and it worked for me (both the versions before and after that commit). I don't know why it is there though. Can we remove it?

See also [bug 1035091](https://bugzilla.mozilla.org/show_bug.cgi?id=1035091) of Firefox.

### PR DESCRIPTION
**Pull request by lilydjwg**
with https://bugzilla.mozilla.org/show_bug.cgi?id=1035091

This closes #904.

### CODE REVIEW

**Comment by lydell** [comment]
Hi! Sorry, I completely forgot about this? Should I merge this and make a release?

**Comment by lilydjwg** [comment]
Well, actually I don't care much as I'm still using 20171130. The removal of `@-moz-document` has broken several websites, including one I use everyday.

When that bug is resolved and I upgrade again, I still can manually edit VimFx.

I hope this change won't break for anyone. Also, no user other than me is affected by this? Did they all give up Firefox Quantum and switch to ESR / Palemoon / Waterfox?

**Comment by kevincox** [comment]
Is there anything preventing this from being merged? Having an icon is nice :)

**Comment by lydell** [comment]
@kevincox I'll merge this at the same time as your PR,

**Pull request merged**
