### PR TITLE
WIP: Hints improvements

### PR DESCRIPTION
**Pull request by lydell**

### CODE REVIEW

**Comment by lydell** [comment]
Since commit 1e75afb it’s really cool to view hint markers on this page. Every commit in the list above has a link to my profile and they all get the same hint :)

**Comment by TheGreenHabi** [comment]
New hints generation is working really well. But sometimes it generates too much hints. For example, in Google Calendar. Seems like combine function needs some update. And maybe update for `vf - command_marker_focus` to work with new algorithms?

It's still possible to compare by using `vf` and `f`
New one, `f` key
f_key

old `vf`
vf

**Comment by lydell** [comment]
I just pushed a commit that reduces the number of hints on Google Calendar.

**Comment by TheGreenHabi** [comment]
Thank you! I will begin testing it

**Pull request merged**
