### PR TITLE
export isXULDocument from utils and fix Ci.nsIDOMElement gone

### LINKED ISSUE #917: 0.20.13 broke Firefox/Waterfox 56 and older
I think one of the last commits killed follow functionality.

Waterfox version 56.1.0 (64-bit)
Is it fixable?

### PR DESCRIPTION
**Pull request by lilydjwg**
This should fix #917 and #918.

(I don't know why this was missing for such a long time while it still worked for me....)

### CODE REVIEW

**Comment by lilydjwg** [comment]
Don't merge yet. I'm still testing.

**Comment by lilydjwg** [comment]
I get an error where `Ci.nsIDOMElement` being `undefined`:

```
TypeError: invalid 'instanceof' operand Element markable-elements.js:33:9 
```

Issues described in #917 is still there.

**Comment by jiixyj** [comment]
I'm getting the same thing with Firefox nightly. Maybe it works with Firefox release/Waterfox, though?

**Comment by jiixyj** [comment]
Yes, I can confirm that it works again in nightly.

**Pull request merged**
