### PR TITLE
Fix #440: Hint markers on feedly.com

### LINKED ISSUE #440: No hints for feedly.com
Hi.
Hints are not generated for most of feedly.com
I use VimFX dev. channel build I compiled on 2015-01-19, Win 8.1, Firefox beta 36

### PR DESCRIPTION
**Pull request by TheGreenHabi**
Fix #440: Hint markers on feedly.com

### CODE REVIEW

**Comment by lydell** [comment]
Please change the commit message to “Fix #440: Hint markers on feedly.com”. Then I’ll merge.

**Comment by lydell** [comment]
I just noticed that you changed the GitHub title of this PR. I meant the _commit message_ :)

**Comment by TheGreenHabi** [comment]
Changed :) Should I remove all other text?

**Comment by lydell** [comment]
Yes.

**Comment by lydell** [comment]
Bump. Got 10 seconds to spare?

**Comment by TheGreenHabi** [comment]
Sure

**Comment by TheGreenHabi** [comment]
OK. I think we misunderstood each other. I thought I changed commit message but apparently I changed not what you wanted me to change. Only other place I haven't changes is commit message attached to changed file. And I cannot find a way to do this with github. Only with git command line, but I never used it and don't know how to setup it to work with this exact patch

**Comment by lydell** [comment]
Merged manually is commit fc6cdd34. Thanks for your contribution! If you consider doing it again in the future I strongly recommend trying the CLI. It’s both easy to install and use!

**Comment by TheGreenHabi** [comment]
Thank you, lydell! Sorry for trouble with this merge. I'm closing this pull request.

**Pull request closed without merging**
