### PR TITLE
Youtube space

### PR DESCRIPTION
**Pull request by lydell**

### CODE REVIEW

**Comment by lydell** [comment]
@TheGreenHabi could you try this out and see if it works?

**Comment by TheGreenHabi** [comment]
Currently I'm testing. Will be back shortly.

**Comment by TheGreenHabi** [comment]
Thank you, lydell! It works in fullscreen mode, no problems. It doesn't work for video player when it's not fullscreen, but I think it's expected behavior.

Also, I run into strange issue while trying to test VimFx. Not related to this particular patch.
What I did:
1. Before updating to Youtube space VimFx patch I decided to add space shortcut for _Scroll full page down_
2. Opened keyboard shortcuts and typed `<space>`. But instead it turned to ` ` At least, it was just empty space. It raised my alert, because I never saw this before.
3. I removed and typed again `<space>`. Again just empty space I can click and remove it
4. I noticed version is 0.5.17. I thought VimFx auto-updated again (so I turned auto-update off)
5. Downloaded _Youtube space patch_. Built it. Installed. VimFx doesn't work. I restarted. It doesn't work. I downloaded current dev build. VimFx doesn't work again.
6. I reset preferences, install _dev build_. It works.
7. I install _Youtube space patch_ - everything is ok.

My thought is VimFx autoupdated to 0.5.17 and somehow typing in spacebar messed up everything. Because even if it autoupdated to 0.5.17 from dev build, it worked, because I opened keyboard shortcuts with `?` key

**Comment by TheGreenHabi** [comment]
P.S. This is log file from Broswer Console when youtube played is not fullscreen and I "focused" on play button with mouse click. And then I press spacebar twice. It works this way.

"[Player Listener] Event onStateChange was called with" Array [ 1, 1 ] YouTubeCenter.js:2022:25
"[Tab Event] Calling player.pauseVideo();" YouTubeCenter.js:2022:25
"[Title Listener] "title" => "title""" YouTubeCenter.js:2022:25
"[Title Listener] "title"" => "title""" YouTubeCenter.js:2022:25
"YouTube configuration data is inaccessible; giving up on language auto-detection." YouTubeCenter.js:2022:25
"[Player Listener] Event onStateChange was called with" Array [ 2, 1 ]

**Comment by lydell** [comment]
> when youtube player is not fullscreen and I "focused" on play button with mouse click. And then I press spacebar twice. It works this way.

Even if VimFx is not installed you need to focus the video player in order for `<space>` to play/pause. Or am I wrong? Using VimFx you should also be able to use the 'f' command to focus.

**Comment by TheGreenHabi** [comment]
Yes, in vanilla youtube there is need to focus video player. But I use _YouTube Center_ GreeseMonkey script, so it somehow removes this step

**Comment by lydell** [comment]
I see. There’s nothing we can do about your YouTube Center GreaseMonkey script. There are a few things you can do though:

- Press `I<space>`.
- Focus the player before hitting space.
- Ask the author of the script to add an “automatically focus the player” option.
- Blacklist `<space>` on youtube: Add `*youtube.com*##<space>` to the blacklist (this is a new yet undocumented feature thanks to #425).

**Pull request merged**
